Лабораторна робота 1.
Вступ до машинного навчання. Елементи лінійної алгебри. Варіант 17.

Завдання 1.
Створіть одновимірний масив (вектор) з числами, які є квадратами натуральних
чисел, починаючи з 1, та виведіть його значення

In [ ]:
import numpy as np

# Створюємо вектор квадратів натуральних чисел
vector = np.array([i**2 for i in range(1, 11)])
print("Вектор квадратів натуральних чисел:", vector)


Вектор квадратів натуральних чисел: [  1   4   9  16  25  36  49  64  81 100]


Завдання 2.
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
випадкових цілих чисел від 1 до 5.


In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
print("Матриця 3x3 з випадковими цілими числами від 1 до 5:\n", matrix)


Матриця 3x3 з випадковими цілими числами від 1 до 5:
 [[4 4 1]
 [5 2 3]
 [2 1 5]]


Завдання 3.
Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 5 та знайдіть максимальне значення за рядком.

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
max_values = matrix.max(axis=1)
print("Матриця:\n", matrix)
print("Максимальні значення за рядком:", max_values)


Матриця:
 [[1 1 5]
 [4 5 4]
 [1 1 1]]
Максимальні значення за рядком: [5 5 1]


Завдання 4.
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 10 та знайдіть вектор-стовпчик, що містить мінімальні елементи в
кожному рядку.

In [ ]:
matrix = np.random.uniform(0, 10, size=(3, 3))
min_values = matrix.min(axis=1)
print("Матриця:\n", matrix)
print("Мінімальні елементи в кожному рядку:", min_values)


Матриця:
 [[8.40874751 4.19584857 6.68044555]
 [3.63466973 7.67435171 5.85748303]
 [6.79403271 9.04131662 0.17739421]]
Мінімальні елементи в кожному рядку: [4.19584857 3.63466973 0.17739421]


Завдання 5.
Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання ta
множення.

In [ ]:
vector1 = np.random.random(6)
vector2 = np.random.random(6)

addition = vector1 + vector2
subtraction = vector1 - vector2
multiplication = vector1 * vector2

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Вектор 1: [0.32789992 0.84345242 0.04407579 0.90112375 0.33719189 0.28341865]
Вектор 2: [0.99796014 0.44120519 0.06809962 0.05660738 0.90683716 0.12515415]
Додавання: [1.32586006 1.28465762 0.11217542 0.95773113 1.24402905 0.4085728 ]
Віднімання: [-0.67006022  0.40224723 -0.02402383  0.84451637 -0.56964528  0.1582645 ]
Множення: [0.32723105 0.37213559 0.00300154 0.05101025 0.30577814 0.03547102]


Завдання 6.
Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 0 до 10 та
знайдіть їх добуток.

In [ ]:
matrix1 = np.random.randint(0, 11, size=(4, 4))
matrix2 = np.random.randint(0, 11, size=(4, 4))
product = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
print("Добуток матриць:\n", product)


Матриця 1:
 [[ 1  3  0  9]
 [ 1  3  1  9]
 [ 8  3 10  2]
 [ 0  9  5  2]]
Матриця 2:
 [[ 7  8  6  6]
 [ 0 10  3  6]
 [ 1  7  0  0]
 [ 4  4  5  0]]
Добуток матриць:
 [[ 43  74  60  24]
 [ 44  81  60  24]
 [ 74 172  67  66]
 [ 13 133  37  54]]


Завдання 7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 5, size=(3, 2))
matrix2 = np.random.randint(1, 5, size=(2, 4))
product = np.dot(matrix1, matrix2)

print("Матриця 3x2:\n", matrix1)
print("Матриця 2x4:\n", matrix2)
print("Добуток матриць:\n", product)


Матриця 3x2:
 [[1 4]
 [4 4]
 [3 1]]
Матриця 2x4:
 [[2 1 2 1]
 [3 2 3 3]]
Добуток матриць:
 [[14  9 14 13]
 [20 12 20 16]
 [ 9  5  9  6]]


Завдання 8.
Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.


In [ ]:
matrix = np.random.randint(1, 9, size=(2, 2))
inverse_matrix = np.linalg.inv(matrix)

print("Матриця:\n", matrix)
print("Обернена матриця:\n", inverse_matrix)


Матриця:
 [[5 2]
 [1 4]]
Обернена матриця:
 [[ 0.22222222 -0.11111111]
 [-0.05555556  0.27777778]]


Завдання 9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 0 до 1 та транспонуйте її.

In [ ]:
matrix = np.random.randint(0, 2, size=(3, 3))
transposed_matrix = np.transpose(matrix)

print("Матриця:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)


Матриця:
 [[1 0 0]
 [0 1 0]
 [0 1 0]]
Транспонована матриця:
 [[1 0 0]
 [0 1 1]
 [0 0 0]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
matrix = np.random.random((3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
product = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток матриці на вектор:\n", product)


Матриця:
 [[0.04260394 0.79258096 0.33410716 0.42213276]
 [0.0413624  0.7809454  0.88738815 0.1976209 ]
 [0.96387916 0.31174863 0.77686225 0.41160538]]
Вектор:
 [[3]
 [6]
 [6]
 [7]]
Добуток матриці на вектор:
 [[ 9.8428699 ]
 [11.5174348 ]
 [12.30454041]]


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.


In [ ]:
matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.randint(1, 11, size=(3, 1))
product = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Добуток матриці на вектор:\n", product)


Матриця:
 [[1 3 5]
 [5 7 5]]
Вектор:
 [[10]
 [ 2]
 [ 2]]
Добуток матриці на вектор:
 [[26]
 [74]]


Завдання 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть суму елементів діагоналі для обох матриць (окремо).

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

diag_sum1 = np.trace(matrix1)
diag_sum2 = np.trace(matrix2)

print("Матриця 1:\n", matrix1)
print("Сума діагоналі:", diag_sum1)
print("Матриця 2:\n", matrix2)
print("Сума діагоналі:", diag_sum2)


Матриця 1:
 [[ 4 10]
 [ 1  9]]
Сума діагоналі: 13
Матриця 2:
 [[6 4]
 [2 7]]
Сума діагоналі: 13


Завдання 13. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть суму їх елементів.

In [ ]:
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))
total_sum = np.sum(matrix1) + np.sum(matrix2)

print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
print("Сума елементів обох матриць:", total_sum)


Матриця 1:
 [[0.91551319 0.99410279 0.44115714]
 [0.4475013  0.09490331 0.25469803]
 [0.0321103  0.08673669 0.24940056]]
Матриця 2:
 [[0.18424529 0.75171052 0.17457647]
 [0.90075221 0.06356681 0.56372385]
 [0.25574755 0.6159248  0.95010863]]
Сума елементів обох матриць: 7.976479433488934


Завдання 14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -5 до 5 та знайдіть середнє геометричне значення елементів матриці.


In [ ]:
matrix = np.random.uniform(-5, 5, size=(3, 3))
geometric_mean = np.exp(np.mean(np.log(matrix + 5)))  # зсув на 5 для уникнення проблем з негативними значеннями

print("Матриця:\n", matrix)
print("Середнє геометричне значення елементів матриці:", geometric_mean)


Матриця:
 [[-0.68500071  4.06792454  4.79196104]
 [-2.85990695 -1.28262278 -0.57424507]
 [-2.96913964 -0.18091846 -2.40566084]]
Середнє геометричне значення елементів матриці: 4.120644192149657


Завдання 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить кількість додатних
елементів в кожному рядку матриці.


In [ ]:
matrix = np.random.random((3, 3))
positive_counts = np.sum(matrix > 0, axis=1)

print("Матриця:\n", matrix)
print("Кількість додатних елементів у кожному рядку:", positive_counts)


Матриця:
 [[0.64552428 0.13474383 0.31457478]
 [0.17270562 0.62216402 0.67716057]
 [0.22777591 0.99911957 0.60151052]]
Кількість додатних елементів у кожному рядку: [3 3 3]


Висновок: У цій лабораторній роботі ми застосували елементи лінійної алгебри для створення та маніпуляції векторами і матрицями за допомогою бібліотеки NumPy. Це дало нам можливість ознайомитися з базовими операціями, такими як поелементне додавання, множення, транспонування, знаходження оберненої матриці тощо, що є основними елементами для подальшого вивчення машинного навчання.